export const FETCH_ORDERS = {
  REQUEST: 'FETCH_ORDERS_REQUEST',
  SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FAILED: 'FETCH_ORDERS_FAILED',
}
export const DELIVER_ORDER = {
  REQUEST: 'DELIVER_ORDER_REQUEST',
  SUCCESS: 'DELIVER_ORDER_SUCCESS',
  FAILED: 'DELIVER_ORDER_FAILED',
}
