//Billing actions
export const ORDERS_TEST_ACTION = 'ORDERS_TEST_ACTION'
export const ORDERS_TEST_ACTION_SUCCESS = 'ORDERS_TEST_ACTION_SUCCESS'
export const ORDERS_TEST_ACTION_FAILED = 'ORDERS_TEST_ACTION_FAILED'
export const ORDERS_TEST_PLAIN_ACTION = 'ORDERS_TEST_PLAIN_ACTION'
