export const FETCH_ORDERS = {
  REQUEST: 'FETCH_ORDERS_REQUEST',
  SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FAILED: 'FETCH_ORDERS_FAILED',
}
export const DELIVER_ORDER = {
  REQUEST: 'DELIVER_ORDER_REQUEST',
  SUCCESS: 'DELIVER_ORDER_SUCCESS',
  FAILED: 'DELIVER_ORDER_FAILED',
}

export const TAKE_ORDER = {
  LOADING: 'TAKE_ORDER_LOADING',
  REQUEST: 'TAKE_ORDER_REQUEST',
  SUCCESS: 'TAKE_ORDER_SUCCESS',
  FAILED: 'TAKE_ORDER_FAILED',
}
