//Billing actions
export const BILLING_TEST_ACTION = 'BILLING_TEST_ACTION'
export const BILLING_TEST_ACTION_SUCCESS = 'BILLING_TEST_ACTION_SUCCESS'
export const BILLING_TEST_ACTION_FAILED = 'BILLING_TEST_ACTION_FAILED'
export const BILLING_TEST_PLAIN_ACTION = 'BILLING_TEST_PLAIN_ACTION'
