//Billing actions
export const REPORTS_TEST_ACTION = 'REPORTS_TEST_ACTION'
export const REPORTS_TEST_ACTION_SUCCESS = 'REPORTS_TEST_ACTION_SUCCESS'
export const REPORTS_TEST_ACTION_FAILED = 'REPORTS_TEST_ACTION_FAILED'
export const REPORTS_TEST_PLAIN_ACTION = 'REPORTS_TEST_PLAIN_ACTION'
