
export const FETCH_USER = {
  REQUEST: 'FETCH_USER_REQUEST',
  SUCCESS: 'FETCH_USER_SUCCESS',
  FAILED: 'FETCH_USER_FAILED',
}
export const UPDATE_USER = {
  REQUEST: 'UPDATE_USER_REQUEST',
  SUCCESS: 'UPDATE_USER_SUCCESS',
  FAILED: 'UPDATE_USER_FAILED',
}

export const DELETE_USER = {
  REQUEST: 'DELETE_USER_REQUEST',
  SUCCESS: 'DELETE_USER_SUCCESS',
  FAILED: 'DELETE_USER_FAILED',
}
export const ADD_USER = {
  REQUEST: 'ADD_USER_REQUEST',
  SUCCESS: 'ADD_USER_SUCCESS',
  FAILED: 'ADD_USER_FAILED',
}
