//Billing actions
export const USERS_TEST_ACTION = 'USERS_TEST_ACTION'
export const USERS_TEST_ACTION_SUCCESS = 'USERS_TEST_ACTION_SUCCESS'
export const USERS_TEST_ACTION_FAILED = 'USERS_TEST_ACTION_FAILED'
export const USERS_TEST_PLAIN_ACTION = 'USERS_TEST_PLAIN_ACTION'
