//Billing actions
export const TABLES_TEST_ACTION = 'TABLES_TEST_ACTION'
export const TABLES_TEST_ACTION_SUCCESS = 'TABLES_TEST_ACTION_SUCCESS'
export const TABLES_TEST_ACTION_FAILED = 'TABLES_TEST_ACTION_FAILED'
export const TABLES_TEST_PLAIN_ACTION = 'TABLES_TEST_PLAIN_ACTION'
export const UPDATE_TABLE = 'UPDATE_TABLE'

export const FETCH_TABLE = {
  REQUEST: 'FETCH_TABLE_REQUEST',
  SUCCESS: 'FETCH_TABLE_SUCCESS',
  FAILED: 'FETCH_TABLE_FAILED',
}
export const FETCH_ORDER_MENU = {
  REQUEST: 'FETCH_ORDER_MENU_REQUEST',
  SUCCESS: 'FETCH_ORDER_MENU_SUCCESS',
  FAILED: 'FETCH_ORDER_MENU_FAILED',
}

export const TAKE_ORDER = {
  LOADING: 'TAKE_ORDER_LOADING',
  REQUEST: 'TAKE_ORDER_REQUEST',
  SUCCESS: 'TAKE_ORDER_SUCCESS',
  FAILED: 'TAKE_ORDER_FAILED',
}

export const DELIVER_ORDER = {
  REQUEST: 'DELIVER_ORDER_REQUEST',
  SUCCESS: 'DELIVER_ORDER_SUCCESS',
  FAILED: 'DELIVER_ORDER_FAILED',
}
