//Billing actions
export const TABLES_TEST_ACTION = 'TABLES_TEST_ACTION'
export const TABLES_TEST_ACTION_SUCCESS = 'TABLES_TEST_ACTION_SUCCESS'
export const TABLES_TEST_ACTION_FAILED = 'TABLES_TEST_ACTION_FAILED'
export const TABLES_TEST_PLAIN_ACTION = 'TABLES_TEST_PLAIN_ACTION'
