//Billing actions
export const DASHBOARD_TEST_ACTION = 'DASHBOARD_TEST_ACTION'
export const DASHBOARD_TEST_ACTION_SUCCESS = 'DASHBOARD_TEST_ACTION_SUCCESS'
export const DASHBOARD_TEST_ACTION_FAILED = 'DASHBOARD_TEST_ACTION_FAILED'
export const DASHBOARD_TEST_PLAIN_ACTION = 'DASHBOARD_TEST_PLAIN_ACTION'
