//Billing actions
export const DASHBOARD_TEST_ACTION = 'DASHBOARD_TEST_ACTION'
export const DASHBOARD_TEST_ACTION_SUCCESS = 'DASHBOARD_TEST_ACTION_SUCCESS'
export const DASHBOARD_TEST_ACTION_FAILED = 'DASHBOARD_TEST_ACTION_FAILED'
export const DASHBOARD_TEST_PLAIN_ACTION = 'DASHBOARD_TEST_PLAIN_ACTION'
export const SHOW_INFORMATIVE_DIALOG = 'SHOW_INFORMATIVE_DIALOG'
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING'
export const DASHBOARD_SNACKBAR = 'DASHBOARD_SNACKBAR'
