export const MODAL_TOGGLE = 'MODAL_TOGGLE'
export const DISPATCH_ORDER = {
  LOADING: 'DISPATCH_ORDER_LOADING',
  REQUEST: 'DISPATCH_ORDER_REQUEST',
  SUCCESS: 'DISPATCH_ORDER_SUCCESS',
  FAILED: 'DISPATCH_ORDER_FAILED',
}
