export const MODAL_TOGGLE = 'MODAL_TOGGLE'
export const TAKE_ORDER = {
  LOADING: 'TAKE_ORDER_LOADING',
  REQUEST: 'TAKE_ORDER_REQUEST',
  SUCCESS: 'TAKE_ORDER_SUCCESS',
  FAILED: 'TAKE_ORDER_FAILED',
}
