//Billing actions
export const KITCHEN_TEST_ACTION = 'KITCHEN_TEST_ACTION'
export const KITCHEN_TEST_ACTION_SUCCESS = 'KITCHEN_TEST_ACTION_SUCCESS'
export const KITCHEN_TEST_ACTION_FAILED = 'KITCHEN_TEST_ACTION_FAILED'
export const KITCHEN_TEST_PLAIN_ACTION = 'KITCHEN_TEST_PLAIN_ACTION'

export const FETCH_PENDING_DISHES = {
  LOADING: 'FETCH_PENDING_DISHES_LOADING',
  REQUEST: 'FETCH_PENDING_DISHES_REQUEST',
  SUCCESS: 'FETCH_PENDING_DISHES_SUCCESS',
  FAILED: 'FETCH_PENDING_DISHES_FAILED',
}
export const DISPATCH_PRODUCT = {
  LOADING: 'DISPATCH_PRODUCT_LOADING',
  REQUEST: 'DISPATCH_PRODUCT_REQUEST',
  SUCCESS: 'DISPATCH_PRODUCT_SUCCESS',
  FAILED: 'DISPATCH_PRODUCT_FAILED',
}
export const CANCEL_PRODUCT = {
  LOADING: 'CANCEL_PRODUCT_LOADING',
  REQUEST: 'CANCEL_PRODUCT_REQUEST',
  SUCCESS: 'CANCEL_PRODUCT_SUCCESS',
  FAILED: 'CANCEL_PRODUCT_FAILED',
}
export const DISPATCH_ORDER = {
  LOADING: 'DISPATCH_ORDER_LOADING',
  REQUEST: 'DISPATCH_ORDER_REQUEST',
  SUCCESS: 'DISPATCH_ORDER_SUCCESS',
  FAILED: 'DISPATCH_ORDER_FAILED',
}
