//Billing actions
export const KITCHEN_TEST_ACTION = 'KITCHEN_TEST_ACTION'
export const KITCHEN_TEST_ACTION_SUCCESS = 'KITCHEN_TEST_ACTION_SUCCESS'
export const KITCHEN_TEST_ACTION_FAILED = 'KITCHEN_TEST_ACTION_FAILED'
export const KITCHEN_TEST_PLAIN_ACTION = 'KITCHEN_TEST_PLAIN_ACTION'

export const FETCH_PENDING_ORDERS = {
    LOADING: 'FETCH_PENDING_ORDERS_LOADING',
    REQUEST: 'FETCH_PENDING_ORDERS_REQUEST',
    SUCCESS: 'FETCH_PENDING_ORDERS_SUCCESS',
    FAILED: 'FETCH_PENDING_ORDERS_FAILED',
  }